[package]
name = "ariko"
version = "0.1.0"
authors = ["Eugenio Depalo <eugeniodepalo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sam3x8e = { path = "./sam3x8e" }
cortex-m = "0.7.1"
cortex-m-rt = "0.6.13"
panic-halt = "0.2.0"
